import type { NextPage } from 'next'
import Head from 'next/head'
import { Brands } from '../components/brand/brand_list'
import { Navbar } from '../components/navbar'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <Brands />
        </div>
    )
}

export default Home
